begin;
create temporary table test_ids(k text primary key,id uuid);
insert into test_ids values('buyer',gen_random_uuid()),('other',gen_random_uuid()),('seller',gen_random_uuid()),('admin',gen_random_uuid()),('super',gen_random_uuid()),('pick',gen_random_uuid());
insert into auth.users(id,email,email_confirmed_at,raw_user_meta_data) select id,id::text||'@test.invalid',now(),jsonb_build_object('full_name','Compliance Test','requested_role',case when k='seller' then 'tipster' else 'bettor' end) from test_ids where k<>'pick';
update public.profiles set role='admin' where id=(select id from test_ids where k='admin');
update public.profiles set role='super_admin' where id=(select id from test_ids where k='super');
update public.tipsters set verification_status='active' where user_id=(select id from test_ids where k='seller');
grant select on test_ids to authenticated;
select set_config('request.jwt.claim.sub',(select id::text from test_ids where k='seller'),true);
set local role authenticated;
do $$ begin
 begin insert into public.predictions(tipster_id,title,sport,match_name,prediction_text,betslip_code,odds,price_tzs,match_date,status) select id,'Test','Football','private','private','private',2,2000,now()+interval '1 day','pending' from public.tipsters where user_id=auth.uid(); raise exception 'FAIL no seller consent'; exception when others then if sqlerrm='FAIL no seller consent' then raise;end if;end;
 begin perform public.accept_policies('old','en',false);raise exception 'FAIL old version';exception when others then if sqlerrm='FAIL old version' then raise;end if;end;
 begin perform public.accept_policies('2026-09-05','sw',true);raise exception 'FAIL outdated seller agreement';exception when raise_exception then if sqlerrm like 'FAIL%' then raise;end if;end;
 perform public.accept_policies('2026-09-05-v2','sw',true);
 perform public.accept_policies('2026-09-05-v2','sw',true);
 if (select count(*) from public.policy_acceptances)<>4 then raise exception 'FAIL acceptance idempotency';end if;
 begin update public.policy_acceptances set accepted_at='2000-01-01';raise exception 'FAIL acceptance mutable';exception when insufficient_privilege then null;end;
end $$;
reset role;
insert into public.predictions(id,tipster_id,title,sport,match_name,prediction_text,betslip_code,odds,price_tzs,match_date,status,bookmaker) select (select id from test_ids where k='pick'),id,'Compliance test','Football','private teams','private picks','private code',2,2000,now()+interval '1 day','pending','BetPawa' from public.tipsters where user_id=auth.uid();
reset role;
update public.predictions set status='published' where id=(select id from test_ids where k='pick');
select set_config('request.jwt.claim.sub',(select id::text from test_ids where k='buyer'),true);
set local role authenticated;
do $$ begin
 begin perform public.create_purchase((select id from test_ids where k='pick'));raise exception 'FAIL purchase bypass';exception when others then if sqlerrm='FAIL purchase bypass' then raise;end if;end;
 perform public.accept_policies('2026-09-05-v2','en',false);
 perform public.create_purchase((select id from test_ids where k='pick'));
 perform public.accept_policies('2026-09-05-v2','en',true);
 perform public.accept_policies('2026-09-05-v2','en',true);
 if (select count(*) from public.tipsters where user_id=auth.uid())<>1 then raise exception 'FAIL duplicate seller account';end if;
 if (select platform_commission_tzs from public.purchases where user_id=auth.uid())<>600 or (select tipster_commission_tzs from public.purchases where user_id=auth.uid())<>400 then raise exception 'FAIL 40/60';end if;
 perform public.request_privacy('deletion','Please close my account and review retention.');
 perform public.export_my_data();
 if exists(select 1 from public.policy_acceptances where user_id<>auth.uid()) then raise exception 'FAIL other consent visible';end if;
 begin perform public.admin_compliance_read('kyc','Attempted access by buyer');raise exception 'FAIL KYC leak';exception when others then if sqlerrm='FAIL KYC leak' then raise;end if;end;
 begin perform public.admin_staff_access(auth.uid(),true,true,true,true,'Attempted privilege escalation');raise exception 'FAIL privilege escalation';exception when others then if sqlerrm='FAIL privilege escalation' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from test_ids where k='admin'),true);
set local role authenticated;
do $$ begin
 if exists(select 1 from public.profiles where id<>auth.uid()) then raise exception 'FAIL generic admin private profile';end if;
 if exists(select 1 from public.purchases) then raise exception 'FAIL generic admin payment read';end if;
 if exists(select 1 from public.audit_logs) then raise exception 'FAIL unaudited audit read';end if;
 begin perform public.admin_verify_manual_payment(gen_random_uuid(),0);raise exception 'FAIL unassigned finance';exception when others then if sqlerrm not like '%Finance permission required%' then raise;end if;end;
 begin perform public.admin_compliance_read('requests','Generic moderation is insufficient');raise exception 'FAIL unassigned privacy';exception when others then if sqlerrm='FAIL unassigned privacy' then raise;end if;end;
end $$;
reset role;
select set_config('request.jwt.claim.sub',(select id::text from test_ids where k='super'),true);
set local role authenticated;
select public.admin_staff_access((select id from test_ids where k='admin'),true,false,false,false,'Assign privacy officer for test');
reset role;
select set_config('request.jwt.claim.sub',(select id::text from test_ids where k='admin'),true);
set local role authenticated;
select public.admin_compliance_read('requests','Review requested account closure');
do $$ declare rid uuid;begin
 select (r->>'id')::uuid into rid from jsonb_array_elements(public.admin_compliance_read('requests','Locate test account deletion')) r where r->>'user_id'=(select id::text from test_ids where k='buyer');
 perform public.admin_restrict_account(rid,'Retain purchase and consent evidence pending approved schedule.');
 begin perform public.admin_compliance_read('kyc','Privacy does not confer KYC access');raise exception 'FAIL scope separation';exception when others then if sqlerrm='FAIL scope separation' then raise;end if;end;
end $$;
reset role;
do $$ begin
 if not exists(select 1 from public.profiles where id=(select id from test_ids where k='buyer') and status='suspended' and full_name='Closed account') then raise exception 'FAIL restriction';end if;
 if not exists(select 1 from public.purchases where user_id=(select id from test_ids where k='buyer')) then raise exception 'FAIL financial preservation';end if;
 if not exists(select 1 from public.audit_logs where action='restricted_read' and actor_user_id=(select id from test_ids where k='admin')) then raise exception 'FAIL read audit';end if;
 if not exists(select 1 from public.policy_acceptances where user_id=(select id from test_ids where k='buyer')) then raise exception 'FAIL consent preservation';end if;
end $$;
select set_config('request.jwt.claim.sub',(select id::text from test_ids where k='buyer'),true);
set local role authenticated;
do $$ begin
 update public.profiles set full_name='Resurrected' where id=auth.uid();
 if found then raise exception 'FAIL suspended profile change';end if;
 update public.tipsters set display_name='Resurrected' where user_id=auth.uid();
 if found then raise exception 'FAIL suspended public profile change';end if;
 begin perform public.accept_policies('2026-09-05-v2','en',false);raise exception 'FAIL closed account accept';exception when others then if sqlerrm='FAIL closed account accept' then raise;end if;end;
end $$;
reset role;
select 'PASS: consent gates, immutable acceptance, identity version, 40/60, own-data RLS, admin scope separation, audited reads, restriction and preserved records' as result;
rollback;
