'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {ExceptionQueues} from '@/components/exception-queues';
import {createClient} from '@/lib/supabase/client';
import {PageHeading,useLanguage} from '@/components/ui';
export default function Review(){
 const db=useMemo(()=>createClient(),[]);const {t}=useLanguage();const [rows,setRows]=useState<any[]>([]);const [selected,setSelected]=useState<any>(null);const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [offset,setOffset]=useState(0);const [superadmin,setSuperadmin]=useState(false);const [checked,setChecked]=useState(false);const [reason,setReason]=useState('');
 async function rpc(action:string,data:Record<string,unknown>={}){const r=await db.rpc('prediction_review',{p_action:action,p_data:data});if(r.error)throw r.error;return r.data;}
 const failure=(e:any)=>setError(e?.message||t('Could not connect. Try again.','Imeshindwa kuunganika. Jaribu tena.'));
 async function load(page=offset){setLoading(true);setError('');try{setRows(await rpc('list',{offset:page}));}catch(e){failure(e);}finally{setLoading(false);}}
 useEffect(()=>{void load();void db.auth.getUser().then(async({data})=>{if(data.user){const p=await db.from('profiles').select('role').eq('id',data.user.id).single();setSuperadmin(p.data?.role==='super_admin');}})},[]);
 async function open(id:string){setBusy(true);setError('');setSelected(null);setChecked(false);setReason('');try{setSelected(await rpc('get',{id}));}catch(e){failure(e);}finally{setBusy(false);}}
 async function decide(decision:string){if(busy||!checked)return;setBusy(true);setError('');try{await rpc('decide',{id:selected.prediction.id,revision:selected.revision,decision,reason});setSelected(null);setChecked(false);setReason('');await load();}catch(e){failure(e);}finally{setBusy(false);}}
 async function grant(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);setBusy(true);try{await rpc('grant',{email:f.get('email'),enabled:f.get('enabled')==='yes',reason:f.get('reason')});setError(t('Permission saved. It applies only to the verified account with this email.','Ruhusa imehifadhiwa. Inatumika kwa akaunti iliyothibitishwa ya email hii tu.'));}catch(e){failure(e);}finally{setBusy(false);}}
 const reasonLabel=(reason:string)=>({probation:t('First five publications require review','Machapisho matano ya kwanza yanahitaji ukaguzi'),identity_review:t('Identity verification required','Uthibitisho wa utambulisho unahitajika'),integrity_hold:t('Integrity or buyer dispute check','Ukaguzi wa uadilifu au malalamiko'),unusual_performance:t('Unusual performance','Utendaji usio wa kawaida'),near_kickoff:t('Near kickoff','Karibu na muda wa mechi'),odds_or_size:t('Odds or selection count needs review','Odds au idadi ya chaguo inahitaji ukaguzi'),duplicate:t('Possible duplicate','Inaweza kuwa nakala'),correlated_selections:t('Related selections','Chaguo zinazohusiana'),legacy_review:t('Existing review queue','Foleni ya ukaguzi iliyopo')}[reason]||reason);const p=selected?.prediction;
 return <main className="container support-page"><PageHeading eyebrow={t('CONTENT REVIEW','UKAGUZI WA MAUDHUI')} title={t('Review predictions & betslips','Kagua utabiri na mikeka')} description={t('Check the complete submission before publication. Approval does not verify results or guarantee winnings.','Kagua maudhui yote kabla ya kuchapisha. Kuapprove hakuthibitishi matokeo wala kuhakikisha ushindi.')}/><Link className="btn" href="/dashboard">{t('My account','Akaunti yangu')}</Link>{error&&<p role="status" className="notice">{error}</p>}
 <section className="panel"><div className="actions"><h2>{t('Needs Review','Inahitaji Ukaguzi')}</h2><button className="btn" disabled={loading||busy} onClick={()=>void load()}>{t('Refresh','Pakia tena')}</button></div>{loading?<p role="status">{t('Loading…','Inapakia…')}</p>:rows.length?rows.map(r=><article className="support-row" key={r.id}><div><h3>{r.title}</h3><p>{r.display_name} · {r.category==='betslip'?'Betslip':'Prediction'} · {new Date(r.match_date).toLocaleString()}</p><p>{(r.review_reasons||[]).map(reasonLabel).join(' · ')}</p></div><button className="btn" disabled={busy} onClick={()=>void open(r.id)}>{t('Review full submission','Kagua mkeka wote')}</button></article>):<p>{t('No submissions in this queue.','Hakuna mikeka kwenye foleni hii.')}</p>}<div className="actions"><button className="btn" disabled={loading||busy||offset===0} onClick={()=>{setOffset(offset-50);void load(offset-50);}}>{t('Previous','Zilizotangulia')}</button><button className="btn" disabled={loading||busy||rows.length<50} onClick={()=>{setOffset(offset+50);void load(offset+50);}}>{t('Next','Zinazofuata')}</button></div></section>
 {p&&<section className="panel"><h2>{p.title}</h2><p>{p.sport} · {p.league} · {p.bookmaker} · {p.selection_count} {t('selections','chaguo')}</p><p>Odds: {p.odds} · {t('Price','Bei')}: TZS {p.price_tzs} · {t('First event','Mechi ya kwanza')}: {new Date(p.match_date).toLocaleString()}</p><h3>{t('Public preview','Muhtasari wa wazi')}</h3><p style={{whiteSpace:'pre-wrap'}}>{p.analysis}</p><h3>{t('Protected selections','Chaguo zinazolindwa')}</h3><p style={{whiteSpace:'pre-wrap'}}>{p.match_name}</p><p style={{whiteSpace:'pre-wrap'}}>{p.prediction_text}</p><p>{t('Betslip code','Code ya mkeka')}: {p.betslip_code}</p>{selected.selections.map((s:any)=><p key={s.id}>{s.event_id} · {s.market_key} · {s.selection} · {s.odds}</p>)}<label className="support-check"><input type="checkbox" checked={checked} onChange={e=>setChecked(e.target.checked)}/>{t('I have reviewed the preview, selections, bookmaker label and start time.','Nimekagua muhtasari, chaguo, lebo ya bookmaker na muda wa kuanza.')}</label><label>{t('Review note / reason','Maelezo / sababu ya uamuzi')}<textarea value={reason} onChange={e=>setReason(e.target.value)} minLength={10} maxLength={1000} rows={3}/></label><div className="actions"><button className="btn btn-primary" disabled={busy||!checked||reason.trim().length<10||new Date(p.match_date)<=new Date()} onClick={()=>void decide('published')}>{t('Approve & publish','Approve na chapisha')}</button><button className="btn" disabled={busy||!checked||reason.trim().length<10} onClick={()=>void decide('rejected')}>{t('Reject submission','Kataa mkeka')}</button></div></section>}
 <ExceptionQueues/>
 {superadmin&&<details className="panel"><summary>{t('Reviewer permissions','Ruhusa za kuapprove')}</summary><form className="support-form" onSubmit={grant}><label>Email<input name="email" type="email" required/></label><label>{t('Permission','Ruhusa')}<select name="enabled"><option value="yes">{t('Enable review access','Ruhusu kuapprove')}</option><option value="no">{t('Revoke review access','Ondoa ruhusa')}</option></select></label><label>{t('Reason','Sababu')}<input name="reason" required minLength={10} maxLength={500}/></label><button disabled={busy} className="btn">{t('Save permission','Hifadhi ruhusa')}</button></form></details>}
 </main>;
}
