'use client';
import {useEffect,useMemo,useState} from 'react';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {Money,PageHeading,useLanguage} from '@/components/ui';
export default function Revenue(){const db=useMemo(()=>createClient(),[]);const {t}=useLanguage();const [data,setData]=useState<any>(null);const [error,setError]=useState('');
 useEffect(()=>{void db.rpc('platform_revenue_summary').then(({data,error})=>{setData(data);if(error)setError(error.message);});},[db]);
 return <main className="container"><PageHeading eyebrow={t('PARTNER REVENUE','MAPATO YA PARTNER')} title={t('Betslip Pro revenue','Mapato ya Betslip Pro')} description={t('Verified sales, protected tipster earnings and platform tax allocation.','Mauzo yaliyothibitishwa, mapato ya tipsters na akiba ya kodi ya platform.')}/><Link className="btn" href="/dashboard">{t('My account','Akaunti yangu')}</Link>{error?<p role="alert" className="notice">{error}</p>:data?<><div className="stats-grid">{[[t('Verified sales','Mauzo yaliyothibitishwa'),'gross'],[t('Tipsters · 70%','Tipsters · 70%'),'tipster'],[t('Platform · 30%','Platform · 30%'),'platform'],[t('WHT allocation','Akiba ya WHT'),'wht'],[t('Platform after WHT','Platform baada ya WHT'),'platformNet'],[t('Processing costs','Gharama za miamala'),'fees'],[t('Refunded sales','Mauzo yaliyorejeshwa'),'refunds'],[t('Tipster payouts completed','Malipo ya tipsters yaliyokamilika'),'payouts']].map(([label,key])=><article className="card" key={key}><span className="stat-label">{label}</span><b className="stat-value"><Money amount={data[key]}/></b></article>)}</div><section className="panel"><h2>{t('Platform after WHT and processing costs','Platform baada ya WHT na gharama za miamala')}</h2><b className="stat-value"><Money amount={data.platformNet-data.fees}/></b><p className="compact-copy">{t('Before other operating expenses and distributions. WHT is an internal allocation, not a record of tax remittance.','Kabla ya gharama nyingine za uendeshaji na mgawanyo wa faida. WHT ni akiba ya ndani, si rekodi ya kodi iliyowasilishwa.')}</p></section></>:<p role="status">{t('Loading…','Inapakia…')}</p>}</main>;
}
