"use client";
import { FormEvent, useEffect, useMemo, useState } from "react";
import { createClient } from "@/lib/supabase/client";
export default function AdvertiserPage() {
 const db=useMemo(()=>createClient(),[]); const [account,setAccount]=useState<any>(null); const [campaigns,setCampaigns]=useState<any[]>([]); const [message,setMessage]=useState("");
 async function load(){const {data:{user}}=await db.auth.getUser(); if(!user){window.location.assign('/login');return;} const {data,error}=await db.from('advertisers').select('*').eq('user_id',user.id).maybeSingle();setAccount(data);if(error)setMessage(error.message);else if(!data)setMessage('No advertiser application / Hakuna ombi la mtangazaji.');const {data:rows}=await db.from('ad_campaigns').select('*').order('created_at',{ascending:false});setCampaigns(rows||[]);}
 useEffect(()=>{void load()},[]);
 async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget);const {error}=await db.rpc('submit_ad_campaign',{p_name:String(f.get('name')),p_package:String(f.get('package')),p_budget_tzs:Number(f.get('budget'))});setMessage(error?error.message:'Submitted for review / Imetumwa kwa ukaguzi.');if(!error)await load();}
 return <main className="container"><section className="panel"><a href="/dashboard">Dashboard / Dashibodi</a><h1>Advertiser portal / Matangazo</h1><p>Approval status / Hali: {account?.status||'—'}</p><p>Sponsored placements are labelled and do not affect tipster rankings. / Matangazo huwekewa lebo na hayabadili viwango vya tipsters.</p>{message&&<p role="status">{message}</p>}{account?.status==='active'&&<form onSubmit={submit}><label>Campaign / Kampeni<input name="name" required maxLength={120}/></label><label>Package / Kifurushi<select name="package"><option value="starter">Starter</option><option value="growth">Growth</option><option value="premium">Premium</option></select></label><label>Budget TZS / Bajeti<input name="budget" type="number" min="1" step="1" required/></label><button className="btn btn-primary">Submit for review / Tuma kwa ukaguzi</button></form>}</section><section className="panel"><h2>Campaigns / Kampeni</h2>{campaigns.map(c=><article className="card" key={c.id}><strong>{c.name}</strong><p>{c.package} · TZS {c.budget_tzs} · {c.status}</p></article>)}{!campaigns.length&&<p>No campaigns yet / Bado hakuna kampeni.</p>}</section></main>
}
