"use client";
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {safeNext} from '@/lib/auth-next';
export default function AuthForm({initialMode='login'}:{initialMode?:'login'|'signup'}){
 const search=useSearchParams();const router=useRouter();const db=useMemo(()=>createClient(),[]);const next=safeNext(search.get('next'));const [mode,setMode]=useState(initialMode);const [busy,setBusy]=useState(false);const [message,setMessage]=useState(search.get('verification')==='failed'?'Uthibitishaji haujakamilika. Jaribu kuingia tena / Verification failed. Please sign in again.':'');const [providers,setProviders]=useState<{google:boolean;apple:boolean}|null>(null);
 const role=['tipster','advertiser'].includes(search.get('role')||'')?search.get('role')!:'bettor';
 useEffect(()=>{fetch('/api/auth/providers').then(r=>r.json()).then(setProviders).catch(()=>setProviders({google:false,apple:false}));},[]);
 function callback(){return `${window.location.origin}/auth/callback?next=${encodeURIComponent(next)}`;}
 async function social(provider:'google'|'apple'){setBusy(true);setMessage('');const {error}=await db.auth.signInWithOAuth({provider,options:{redirectTo:callback()}});if(error){setMessage(error.message);setBusy(false);}}
 async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const f=new FormData(event.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));
 try{if(mode==='login'){const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;router.replace(next);router.refresh();}else{if(f.get('adult')!=='on')throw new Error('Thibitisha una miaka 18+ / Confirm you are 18+.');const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:callback(),data:{full_name:String(f.get('name')),requested_role:role,locale:'sw',age_confirmed:true}}});if(error)throw error;if(data.session){router.replace(next);router.refresh();}else setMessage('Angalia email yako kuthibitisha account, kisha rudi kwenye slip yako / Check your email to confirm your account, then return to your slip.');}}catch(e){setMessage(e instanceof Error?e.message:'Imeshindikana. Jaribu tena / Please try again.');}finally{setBusy(false);}}
 return <main className="container"><div className="form panel"><Link className="brand" href="/">BETSLIP <span>PRO</span></Link><h1>{mode==='login'?'Karibu tena / Sign in':'Fungua account / Sign up'}</h1><p className="muted">{next.startsWith('/predictions/')?'Ingia au jisajili kuendelea na slip uliyochagua. / Continue with your selected slip.':'Account yako ya Betslip Pro.'}</p><div className="auth-tabs"><button type="button" className={mode==='login'?'btn btn-primary':'btn btn-secondary'} onClick={()=>{setMode('login');setMessage('')}}>Sign in / Ingia</button><button type="button" className={mode==='signup'?'btn btn-primary':'btn btn-secondary'} onClick={()=>{setMode('signup');setMessage('')}}>Sign up / Jisajili</button></div>{role==='bettor'&&<><div className="social-options">{(['google','apple'] as const).map(provider=><button className="btn btn-secondary" type="button" key={provider} disabled={busy||!providers?.[provider]} onClick={()=>void social(provider)}>Continue with {provider==='google'?'Google':'Apple'}{providers&&!providers[provider]?' · Inakuja / Coming soon':''}</button>)}</div><p className="auth-divider">au tumia email / or use email</p></>}<form onSubmit={submit}>{mode==='signup'&&<label>Jina / Name<input name="name" autoComplete="name" required maxLength={120}/></label>}<label>Email<input type="email" name="email" autoComplete="email" required/></label><label>Nenosiri / Password<input type="password" name="password" autoComplete={mode==='login'?'current-password':'new-password'} required minLength={mode==='signup'?8:1}/></label>{mode==='signup'&&<label className="check-label"><input type="checkbox" name="adult" required/>Nina miaka 18+ / I am 18 or older</label>}<button className="btn btn-primary auth-submit" disabled={busy}>{busy?'Subiri / Please wait…':mode==='login'?'Sign in / Ingia':'Sign up / Jisajili'}</button></form>{message&&<p className="notice" role="status">{message}</p>}<p><Link href={next.startsWith('/predictions/')?next.split('?')[0]:'/'}>← Rudi kuangalia slips / Back to browsing</Link></p></div></main>
}
