'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {useSearchParams,useRouter} from 'next/navigation';
import Link from 'next/link';
import {createClient} from '@/lib/supabase/client';
import {safeNext,afterSignIn} from '@/lib/auth-next';
import {Icon,useLanguage} from './ui';
export default function AuthForm({initialMode='login'}:{initialMode?:'login'|'signup'}){const search=useSearchParams();const router=useRouter();const db=useMemo(()=>createClient(),[]);const {t,locale}=useLanguage();const next=safeNext(search.get('next'));const [mode,setMode]=useState(initialMode);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const role=['tipster','advertiser'].includes(search.get('role')||'')?search.get('role')!:'bettor';useEffect(()=>{if(search.get('error')||search.get('verification')==='failed')setMessage(t('Verification failed. Please sign in again.','Uthibitisho umeshindikana. Tafadhali ingia tena.'))},[]);function callback(){return `${window.location.origin}/auth/callback?next=${encodeURIComponent(next)}`}async function submit(event:FormEvent<HTMLFormElement>){event.preventDefault();setBusy(true);setMessage('');const f=new FormData(event.currentTarget);const email=String(f.get('email'));const password=String(f.get('password'));try{if(mode==='login'){const {error}=await db.auth.signInWithPassword({email,password});if(error)throw error;const {data:policy,error:policyError}=await db.rpc('policy_status');router.replace(afterSignIn(next,policyError?null:policy));router.refresh()}else{if(f.get('adult')!=='on')throw new Error(t('Confirm you are 18 or older.','Thibitisha una miaka 18 au zaidi.'));const {data,error}=await db.auth.signUp({email,password,options:{emailRedirectTo:callback(),data:{full_name:String(f.get('name')),requested_role:role,locale,age_confirmed:true}}});if(error)throw error;if(data.session){router.replace('/account/privacy?next='+encodeURIComponent(next));router.refresh()}else setMessage(t('Check your email to confirm your account, then return to sign in.','Angalia email kuthibitisha akaunti yako, kisha rudi kuingia.'))}}catch(e){setMessage(e instanceof Error?e.message:t('Please try again.','Tafadhali jaribu tena.'))}finally{setBusy(false)}}return <main className={`container auth-layout${mode==='signup'?' auth-signup':''}`}>
{mode==='login'&&<aside className="auth-art"><span className="eyebrow">BETSLIP PRO</span><h2>{t('Know the record.\nOwn your decision.','Jua rekodi.\nAmua mwenyewe.').split('\n').map(s=><span style={{display:'block'}} key={s}>{s}</span>)}</h2><p className="muted">{t('Find. Verify. Follow. Buy.','Tafuta. Hakiki. Fuata. Nunua.')}</p></aside>}
<section className="form panel">
<h1>{mode==='login'?t('Sign in','Ingia'):role==='tipster'?t('Create a tipster account','Fungua akaunti ya tipster'):t('Create account','Fungua akaunti')}</h1>
{mode==='signup'&&role==='tipster'&&<p className="compact-copy">{t('Your account will be reviewed before you can publish.','Akaunti yako itakaguliwa kabla ya kuchapisha.')}</p>}
<form key={mode} onSubmit={submit}>
{mode==='signup'&&<label>{t('Full name','Jina kamili')}<input name="name" autoComplete="name" required maxLength={120}/></label>}
<label>Email<input type="email" name="email" autoComplete="email" required placeholder="you@example.com"/></label>
<label>{t('Password','Nenosiri')}<input type="password" name="password" autoComplete={mode==='signup'?'new-password':'current-password'} required minLength={mode==='signup'?8:1} aria-describedby={mode==='signup'?'password-hint':undefined}/>{mode==='signup'&&<small id="password-hint" className="muted">{t('At least 8 characters','Angalau herufi 8')}</small>}</label>
{mode==='signup'&&<label className="check-label"><input name="adult" type="checkbox" required/>{t('I am 18+ and understand there are no guaranteed wins.','Nina miaka 18+ na ninaelewa hakuna uhakika wa ushindi.')}</label>}
<button className="btn btn-primary auth-submit" disabled={busy}>{busy?t('Please wait…','Subiri…'):mode==='login'?t('Sign in','Ingia'):t('Create account','Fungua akaunti')}<Icon name="arrow" size={16}/></button>
</form>
{message&&<p className="notice" role="status">{message}</p>}
<p className="auth-switch">{mode==='signup'?t('Already have an account?','Una akaunti tayari?'):t('New here?','Huna akaunti?')} <button type="button" disabled={busy} onClick={()=>{setMode(mode==='signup'?'login':'signup');setMessage('')}}>{mode==='signup'?t('Sign in','Ingia'):t('Create account','Fungua akaunti')}</button></p>
<p className="compact-copy auth-legal"><Link href="/legal/terms">{t('Terms','Masharti')}</Link> · <Link href="/legal/privacy">{t('Privacy','Faragha')}</Link></p>
</section></main>}
