"use client";
import Link from 'next/link';
import {useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
type Slip={id:string;title:string;sport:string;league:string|null;match_name:string;odds:number|null;price_tzs:number;match_date:string;tipsters:{display_name:string;profile_image_url:string|null}|null};
export default function Marketplace(){
 const db=useMemo(()=>createClient(),[]);const [slips,setSlips]=useState<Slip[]>([]);const [loading,setLoading]=useState(true);const [error,setError]=useState('');const [query,setQuery]=useState('');
 async function load(){setLoading(true);setError('');const {data,error}=await db.from('predictions').select('id,title,sport,league,match_name,odds,price_tzs,match_date,tipsters(display_name,profile_image_url)').eq('status','published').gt('match_date',new Date().toISOString()).order('match_date');if(error)setError('Slips hazijapakia. Jaribu tena / Unable to load slips. Please retry.');else setSlips((data||[]) as unknown as Slip[]);setLoading(false);}
 useEffect(()=>{void load()},[]);
 const shown=slips.filter(s=>[s.title,s.sport,s.league,s.match_name,s.tipsters?.display_name].join(' ').toLowerCase().includes(query.toLowerCase()));
 return <section id="slips" className="market-section"><div className="section-heading"><div><span className="eyebrow">MARKETPLACE / SOKO</span><h2>Slips zinazopatikana</h2><p className="muted">Angalia bure. Ingia unapokuwa tayari kununua. / Browse freely, sign in to buy.</p></div><label className="search-label">Tafuta slips / Search<input type="search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Timu, ligi au tipster…"/></label></div>
 {loading?<p role="status">Inapakia slips / Loading slips…</p>:error?<div className="panel" role="alert"><p>{error}</p><button className="btn" onClick={()=>void load()}>Jaribu tena / Retry</button></div>:shown.length?<div className="grid">{shown.map(s=><article className="card slip-card" key={s.id}><span className="badge">{s.sport}{s.league?` · ${s.league}`:''}</span><h3>{s.title}</h3><p>{s.match_name}</p><p className="muted">{s.tipsters?.display_name||'Tipster'} · {new Date(s.match_date).toLocaleString()}</p><div className="slip-price"><span>Odds <strong>{s.odds??'—'}</strong></span><strong>TZS {s.price_tzs.toLocaleString()}</strong></div><p className="notice">Code na uchambuzi kamili hufunguka baada ya malipo kuthibitishwa.</p><div className="actions"><Link className="btn btn-secondary" href={`/predictions/${s.id}`}>Maelezo / Details</Link><Link className="btn btn-primary" href={`/predictions/${s.id}?buy=1`}>Nunua / Buy</Link></div></article>)}</div>:<div className="empty-market panel"><h3>{query?'Hakuna matokeo / No matches':'Slips mpya zinakuja / New slips coming soon'}</h3><p className="muted">{query?'Jaribu jina la timu, ligi au tipster tofauti.':'Bado hakuna slips zilizochapishwa. Zitapatikana hapa baada ya kupitiwa na admin.'}</p><button className="btn btn-secondary" onClick={()=>query?setQuery(''):void load()}>{query?'Futa utafutaji / Clear search':'Angalia tena / Refresh'}</button></div>}
 </section>
}
