'use client';
import {FormEvent,useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';
import {Money,Status,useLanguage} from '@/components/ui';
export function PayoutOperations(){const db=useMemo(()=>createClient(),[]);const {t}=useLanguage();const [rows,setRows]=useState<any[]>([]);const [balances,setBalances]=useState<any[]>([]);const [message,setMessage]=useState('');const [busy,setBusy]=useState(false);
 async function load(){const b=await db.rpc('finance_wallet_balances');if(b.error)setMessage(b.error.message);else setBalances(b.data||[]);const {data,error}=await db.rpc('payout_queue');if(error)setMessage(error.message);else setRows(data||[]);}useEffect(()=>{void load();},[]);
 async function finish(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const {error}=await db.rpc('finish_payout',{p_id:id,p_decision:f.get('decision'),p_reference:f.get('reference')});if(error)throw error;window.location.reload();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 async function release(e:FormEvent<HTMLFormElement>,id:string){e.preventDefault();setBusy(true);const f=new FormData(e.currentTarget);try{const {error}=await db.rpc('make_tipster_earnings_available',{p_tipster_user_id:id,p_amount_tzs:Number(f.get('amount'))});if(error)throw error;window.location.reload();}catch(e:any){setMessage(e.message);}finally{setBusy(false);}}
 return <section className="panel"><h2>{t('Payout operations','Usimamizi wa kutoa pesa')}</h2>{message&&<p role="alert">{message}</p>}<details><summary>{t('Release verified earnings','Ruhusu mapato yaliyothibitishwa')}</summary><p>{t('Reconcile payment and unresolved refund obligations before releasing earnings.','Hakiki malipo na wajibu wa marejesho kabla ya kuruhusu mapato.')}</p>{balances.map(b=><form key={b.user_id} onSubmit={e=>void release(e,b.user_id)}><h3>{b.display_name}</h3><p>{t('Pending','Inasubiri')}: <Money amount={b.pending_balance_tzs}/> · {t('Available','Inapatikana')}: <Money amount={b.available_balance_tzs}/></p><label>{t('Amount to release · TZS','Kiasi cha kuruhusu · TZS')}<input name="amount" type="number" min="1" max={b.pending_balance_tzs} step="1" required/></label><label><input type="checkbox" required/>{t('I reconciled these earnings.','Nimehakiki mapato haya.')}</label><button disabled={busy||!b.pending_balance_tzs} className="btn">{t('Release to available balance','Hamishia kwenye salio linalopatikana')}</button></form>)}</details>{rows.length?rows.map(w=><article className="card" key={w.id}><h3>{w.display_name} · <Money amount={w.amount_tzs}/></h3><Status value={w.status}/>{['pending','approved'].includes(w.status)&&<form onSubmit={e=>void finish(e,w.id)}><p>{w.payment_method}: {w.account_number}</p><label>{t('Decision','Uamuzi')}<select name="decision"><option value="paid">{t('Transfer completed','Uhamisho umekamilika')}</option><option value="rejected">{t('Reject and release reservation','Kataa na rudisha salio')}</option></select></label><label>{t('Completed transfer reference / rejection reason','Kumbukumbu ya uhamisho / sababu ya kukataa')}<input name="reference" minLength={5} required/></label><label><input type="checkbox" required/>{t('I verified this payout decision.','Nimehakiki uamuzi huu wa malipo.')}</label><button disabled={busy} className="btn">{t('Record decision','Hifadhi uamuzi')}</button></form>}</article>):<p>{t('No payouts requested.','Hakuna maombi ya kutoa pesa.')}</p>}</section>;
}
