'use client';
import {FormEvent,useEffect,useMemo,useRef,useState} from 'react';
import Link from 'next/link';
import {useParams,useRouter} from 'next/navigation';
import {createClient} from '@/lib/supabase/client';
import {PageHeading,useLanguage} from '@/components/ui';

const statuses:Record<string,[string,string]>={open:['New / reopened','Mpya / imefunguliwa tena'],in_progress:['In progress','Inafanyiwa kazi'],waiting_customer:['Waiting for your reply','Inasubiri jibu la mteja'],resolved:['Resolved','Imetatuliwa'],closed:['Closed','Imefungwa']};
const categories:Record<string,[string,string]>={account:['Account','Akaunti'],technical:['Technical problem','Tatizo la mfumo'],payment:['Payment','Malipo'],content:['Purchased content','Maudhui yaliyonunuliwa'],refund:['Refund / purchase review','Refund / ukaguzi wa ununuzi'],general:['Other support','Msaada mwingine']};
type Ticket={id:string;number:number;subject:string;category:string;status:string;assigned_to:string|null;created_at:string;updated_at:string;due_at:string|null;escalated_at:string|null;purchase_id?:string|null;email_updates?:boolean;redacted_at?:string|null};
type Agent={id:string;full_name:string;finance:boolean};
type Boot={staff:boolean;superadmin:boolean;finance:boolean;agents:Agent[];purchases:{id:string;payment_status:string;amount_tzs:number}[]};
type Message={id:string;kind:string;body:string;internal:boolean;created_at:string};
type Detail={ticket:Ticket;messages:Message[];dispute:{id:string;status:string;resolution:string|null;refund_reference:string|null}|null};
const errorText=(error:unknown)=>error&&typeof error==='object'&&'message' in error?String(error.message):'Could not connect. Try again. / Imeshindwa kuunganika. Jaribu tena.';
function TicketStatus({status}:{status:string}){const {t}=useLanguage();const label=statuses[status];return <span className={`support-status support-${status}`}>{label?t(...label):status}</span>}

export function SupportHome({team=false}:{team?:boolean}){
 const db=useMemo(()=>createClient(),[]);const router=useRouter();const {t}=useLanguage();
 const [boot,setBoot]=useState<Boot|null>(null);const [rows,setRows]=useState<Ticket[]>([]);const [loading,setLoading]=useState(true);const [busy,setBusy]=useState(false);const [error,setError]=useState('');
 const [filter,setFilter]=useState(team?'active':'all');const [search,setSearch]=useState('');const [offset,setOffset]=useState(0);const [category,setCategory]=useState('technical');const key=useRef<string|null>(null);const request=useRef(0);
 const [members,setMembers]=useState<{user_id:string;enabled:boolean;full_name:string}[]>([]);
 async function rpc(action:string,payload:Record<string,unknown>={}){const r=await db.rpc('support_api',{p_action:action,p_payload:payload});if(r.error)throw r.error;return r.data;}
 async function load(page=offset,status=filter,query=search){const generation=++request.current;setLoading(true);setError('');try{const b:Boot=await rpc('bootstrap');if(team&&!b.staff)throw new Error(t('Support access is required. Ask the owner to assign it.','Ruhusa ya support inahitajika. Mmiliki anaweza kuikupa.'));const data=await rpc('list',{team,status,search:query,offset:page});if(generation===request.current){setBoot(b);setRows(data);if(b.superadmin&&team)setMembers(await rpc('agents'));}}catch(e){if(generation===request.current)setError(errorText(e));}finally{if(generation===request.current)setLoading(false);}}
 useEffect(()=>{void load();return()=>{request.current++}},[team]);
 async function create(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const f=new FormData(e.currentTarget);key.current??=crypto.randomUUID();try{const result=await rpc('create',{key:key.current,subject:f.get('subject'),category,body:f.get('body'),purchase_id:f.get('purchase')||null,email_updates:f.get('email')==='on'});router.push('/support/'+result.id);}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function member(e:FormEvent<HTMLFormElement>){e.preventDefault();if(busy)return;setBusy(true);setError('');const form=e.currentTarget;const f=new FormData(form);try{setMembers(await rpc('agents',{email:f.get('email'),enabled:f.get('enabled')==='yes',reason:f.get('reason')}));form.reset();await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 return <main className="container support-page">
  <PageHeading eyebrow={team?t('SUPPORT OPERATIONS','USIMAMIZI WA MSAADA'):t('HELP & SUPPORT','MSAADA')} title={team?t('One queue. Clear next steps.','Tickets zote. Hatua zilizo wazi.'):t('Let’s get it sorted.','Tutatue pamoja.')} description={team?t('Tickets arrive automatically. Reply, assign an agent and track what needs attention.','Tickets zinaingia zenyewe. Jibu, panga mhudumu na fuatilia zinazohitaji hatua.'):t('Open a ticket, follow its status and keep the conversation in one place.','Fungua ticket, fuatilia status na endeleza mazungumzo sehemu moja.')}/>
  <div className="actions"><Link className="btn" href="/dashboard">{t('My account','Akaunti yangu')}</Link>{boot?.staff&&<Link className="btn" href={team?'/support':'/support/team'}>{team?t('My tickets','Tickets zangu'):t('Support queue','Foleni ya support')}</Link>}<Link className="btn" href="/feedback">{t('Share an idea','Toa pendekezo')}</Link></div>
  {error&&<p className="notice" role="alert">{error} <button className="btn" disabled={loading} onClick={()=>void load()}>{t('Retry','Jaribu tena')}</button></p>}
  {!team&&boot&&<details className="panel support-create" open={!loading&&rows.length===0}>
   <summary>{t('Open a new ticket','Fungua ticket mpya')}</summary>
   <form onSubmit={create} className="support-form">
    <label>{t('What do you need help with?','Unahitaji msaada gani?')}<select value={category} onChange={e=>setCategory(e.target.value)}>{Object.entries(categories).map(([value,labels])=><option key={value} value={value}>{t(...labels)}</option>)}</select></label>
    {['payment','content','refund'].includes(category)&&<label>{t('Related purchase','Ununuzi unaohusika')}<select name="purchase" required={category==='refund'} defaultValue=""><option value="">{category==='refund'?t('Select a purchase','Chagua ununuzi'):t('No purchase / not listed','Hakuna ununuzi / haupo kwenye orodha')}</option>{boot.purchases.map(p=><option key={p.id} value={p.id}>{p.id.slice(0,8)} · TZS {p.amount_tzs} · {p.payment_status}</option>)}</select></label>}
    <label>{t('Subject','Kichwa cha tatizo')}<input name="subject" required minLength={5} maxLength={140} placeholder={t('For example: my purchased slip will not open','Mfano: slip niliyonunua haifunguki')}/></label>
    <label>{t('What happened?','Nini kilitokea?')}<textarea name="body" required minLength={10} maxLength={2000} rows={5}/></label>
    <p className="muted">{t('Include the page, device and what you expected. Never send passwords, OTPs, PINs, card details or identity documents.','Taja ukurasa, kifaa na ulichotarajia. Usiweke nenosiri, OTP, PIN, taarifa za kadi au nyaraka za utambulisho.')}</p>
    {category==='refund'&&<p className="notice">{t('This opens a purchase review. A ticket does not approve or execute a refund. A losing prediction alone is not a refund reason.','Hii inafungua ukaguzi wa ununuzi. Ticket haiidhinishi wala kutuma refund. Kupoteza utabiri pekee si sababu ya refund.')}</p>}
    <label className="support-check"><input type="checkbox" name="email" defaultChecked/>{t('Email me ticket updates at my verified account email.','Nitumie taarifa za ticket kwenye email iliyothibitishwa ya akaunti yangu.')}</label>
    <p className="muted">{t('No verified email? Updates still appear here and in Activity.','Huna email iliyothibitishwa? Taarifa bado zinaonekana hapa na kwenye Taarifa.')}{' '}<Link href="/account/privacy">{t('Personal data access, correction or deletion','Kupata, kusahihisha au kufuta taarifa binafsi')}</Link></p>
    <button className="btn btn-primary" disabled={busy}>{busy?t('Sending…','Inatuma…'):t('Create ticket','Fungua ticket')}</button>
   </form>
  </details>}
  <section className="panel">
   <h2>{team?t('Support queue','Foleni ya support'):t('Your tickets','Tickets zako')}</h2>
   {team&&<p className="muted">{t('Internal response targets: 4 hours for purchase issues, 24 hours for other tickets. Overdue items escalate hourly; these are internal targets, not guaranteed resolution times.','Malengo ya ndani ya kujibu: saa 4 kwa masuala ya ununuzi, saa 24 kwa mengine. Mfumo hukagua zilizochelewa kila saa; haya si muda wa kuahidi suluhisho.')}</p>}
   <form className="support-filters" onSubmit={e=>{e.preventDefault();setOffset(0);void load(0);}}><label>{t('Status','Status')}<select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">{t('All','Zote')}</option><option value="active">{t('Active tickets','Tickets zinazoendelea')}</option>{team&&<option value="overdue">{t('Overdue','Zimechelewa')}</option>}{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{t(...l)}</option>)}</select></label><label>{t('Find ticket','Tafuta ticket')}<input value={search} onChange={e=>setSearch(e.target.value)} maxLength={100} placeholder={t('Ticket number or subject','Namba ya ticket au kichwa')}/></label><button className="btn" disabled={loading}>{t('Search / refresh','Tafuta / pakia tena')}</button></form>
   {loading?<p role="status">{t('Loading tickets…','Inapakia tickets…')}</p>:rows.length?rows.map(x=><Link className="support-row" key={x.id} href={`${team?'/support/team':'/support'}/${x.id}`}><div><span className="eyebrow">BP-{x.number} · {t(...categories[x.category])}</span><h3>{x.subject}</h3><p className="muted">{new Date(x.updated_at).toLocaleString()}</p></div><div><TicketStatus status={x.status}/>{team&&x.due_at&&new Date(x.due_at)<new Date()&&<p className="negative">{t('Needs attention','Inahitaji hatua')}</p>}{team&&<p className="muted">{boot?.agents.find(a=>a.id===x.assigned_to)?.full_name||t('Unassigned','Haijapangiwa')}</p>}</div></Link>):<p className="muted">{t('No tickets match this view.','Hakuna tickets kwenye chaguo hili.')}</p>}
   <div className="actions"><button className="btn" disabled={loading||offset===0} onClick={()=>{const p=Math.max(0,offset-50);setOffset(p);void load(p);}}>{t('Previous','Zilizotangulia')}</button><button className="btn" disabled={loading||rows.length<50} onClick={()=>{const p=offset+50;setOffset(p);void load(p);}}>{t('Next','Zinazofuata')}</button></div>
  </section>
  {team&&boot?.superadmin&&<details className="panel"><summary>{t('Support team access','Ruhusa za timu ya support')}</summary><p className="muted">{t('Grant support access to a verified registered user. This does not grant admin, finance, KYC or privacy permissions.','Mpe mtumiaji aliyesajiliwa na kuthibitishwa ruhusa ya support. Hii haitoi ruhusa za admin, finance, KYC au faragha.')}</p><form className="support-form" onSubmit={member}><label>Email<input name="email" type="email" required autoComplete="off"/></label><label>{t('Access','Ruhusa')}<select name="enabled"><option value="yes">{t('Enable support access','Washa ruhusa ya support')}</option><option value="no">{t('Revoke support access','Ondoa ruhusa ya support')}</option></select></label><label>{t('Reason for this access change','Sababu ya kubadili ruhusa')}<input name="reason" required minLength={10} maxLength={500}/></label><button disabled={busy} className="btn">{t('Save access','Hifadhi ruhusa')}</button></form>{members.map(m=><p key={m.user_id}>{m.full_name} · {m.enabled?t('Enabled','Imeruhusiwa'):t('Revoked','Imeondolewa')}</p>)}</details>}
 </main>;
}

export function SupportDetail({team=false}:{team?:boolean}){
 const {id}=useParams<{id:string}>();const db=useMemo(()=>createClient(),[]);const {t}=useLanguage();
 const [data,setData]=useState<Detail|null>(null);const [boot,setBoot]=useState<Boot|null>(null);const [error,setError]=useState('');const [busy,setBusy]=useState(false);const [loading,setLoading]=useState(true);const [internal,setInternal]=useState(false);const [status,setStatus]=useState('waiting_customer');const [agent,setAgent]=useState('');const [body,setBody]=useState('');const key=useRef<string|null>(null);
 async function rpc(action:string,payload:Record<string,unknown>={}){const r=await db.rpc('support_api',{p_action:action,p_payload:{...payload,id,team}});if(r.error)throw r.error;return r.data;}
 async function load(){setLoading(true);try{const b:Boot=await rpc('bootstrap');const d:Detail=await rpc('get');setBoot(b);setData(d);setAgent(d.ticket.assigned_to||'');setError('');}catch(e){setData(null);setError(errorText(e));}finally{setLoading(false);}}
 useEffect(()=>{void load()},[id,team]);
 async function reply(e:FormEvent){e.preventDefault();if(busy)return;setBusy(true);setError('');key.current??=crypto.randomUUID();try{await rpc('reply',{key:key.current,body,internal,status});setBody('');key.current=null;await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 async function action(name:string,payload:Record<string,unknown>){if(busy)return;setBusy(true);setError('');try{await rpc(name,payload);await load();}catch(e){setError(errorText(e));}finally{setBusy(false);}}
 const ticket=data?.ticket;
 return <main className="container support-page"><div className="actions"><Link className="btn" href={team?'/support/team':'/support'}>← {t('Tickets','Tickets')}</Link><button className="btn" disabled={busy||loading} onClick={()=>void load()}>{t('Refresh conversation','Pakia mazungumzo')}</button></div>{error&&<p className="notice" role="alert">{error}</p>}{loading&&!ticket&&<p role="status">{t('Loading…','Inapakia…')}</p>}{ticket&&data&&<>
  <PageHeading eyebrow={`BP-${ticket.number} · ${t(...categories[ticket.category])}`} title={ticket.subject} description={t('Keep replies and updates together.','Majibu na taarifa zote zinabaki hapa.')}/>
  <div className="support-meta"><TicketStatus status={ticket.status}/><span>{new Date(ticket.created_at).toLocaleString()}</span>{ticket.purchase_id&&<span>{t('Purchase','Ununuzi')}: {ticket.purchase_id.slice(0,8)}</span>}</div>
  {data.dispute&&<section className="notice"><strong>{t('Purchase review','Ukaguzi wa ununuzi')}: {data.dispute.status}</strong><p>{data.dispute.resolution}</p>{data.dispute.refund_reference&&<p>{t('Transfer reference','Kumbukumbu ya marejesho')}: {data.dispute.refund_reference}</p>}{team&&boot?.finance&&<Link className="btn" href="/admin/compliance">{t('Open finance review','Fungua ukaguzi wa finance')}</Link>}</section>}
  {team&&<section className="panel"><label>{t('Assigned agent','Mhudumu aliyepangiwa')}<select value={agent} onChange={e=>setAgent(e.target.value)}><option value="">{t('Assign automatically','Panga mhudumu moja kwa moja')}</option>{boot?.agents.filter(a=>!['payment','content','refund'].includes(ticket.category)||a.finance).map(a=><option key={a.id} value={a.id}>{a.full_name}</option>)}</select></label><button disabled={busy||agent===(ticket.assigned_to||'')} className="btn" onClick={()=>void action('assign',{agent})}>{t('Save assignment','Hifadhi mhudumu')}</button>{ticket.due_at&&<p className="muted">{t('Internal response target','Lengo la ndani la kujibu')}: {new Date(ticket.due_at).toLocaleString()}</p>}</section>}
  <section className="support-thread" aria-label={t('Conversation','Mazungumzo')}>{data.messages.map(m=><article className={`panel support-message ${m.internal?'support-internal':''}`} key={m.id}><div className="support-meta"><strong>{m.internal?t('Internal team note','Maelezo ya ndani ya timu'):m.kind==='customer'?t('Customer','Mteja'):m.kind==='staff'?t('Support team','Timu ya support'):t('System update','Taarifa ya mfumo')}</strong><time>{new Date(m.created_at).toLocaleString()}</time></div><p>{m.body}</p></article>)}</section>
  {!ticket.redacted_at&&<section className="panel"><h2>{t('Reply','Jibu')}</h2><form className="support-form" onSubmit={reply}><label>{internal?t('Private note — only the support team sees this','Maelezo ya ndani — timu pekee itaona'):t('Message','Ujumbe')}<textarea value={body} onChange={e=>{setBody(e.target.value);key.current=null;}} required maxLength={4000} minLength={team&&!internal&&['resolved','closed'].includes(status)?10:1} rows={5}/></label>{team&&<><label className="support-check"><input type="checkbox" checked={internal} onChange={e=>{setInternal(e.target.checked);key.current=null;}}/>{t('Internal note (not sent to the customer)','Maelezo ya ndani (hayatumwi kwa mteja)')}</label><label>{t('Status after this reply','Status baada ya jibu')}<select disabled={internal} value={status} onChange={e=>{setStatus(e.target.value);key.current=null;}}>{Object.entries(statuses).map(([v,l])=><option key={v} value={v}>{t(...l)}</option>)}</select></label></>}<p className="muted">{t('Never include passwords, OTPs, PINs or identity documents.','Usiweke nenosiri, OTP, PIN au nyaraka za utambulisho.')}{!team&&['resolved','closed'].includes(ticket.status)&&' '+t('Your reply will reopen this ticket.','Jibu lako litafungua ticket hii tena.')}</p><button className="btn btn-primary" disabled={busy}>{busy?t('Saving…','Inahifadhi…'):internal?t('Save internal note','Hifadhi maelezo ya ndani'):t('Send reply','Tuma jibu')}</button></form></section>}
  {!team&&<label className="support-check"><input type="checkbox" checked={!!ticket.email_updates} disabled={busy} onChange={e=>void action('email',{enabled:e.target.checked})}/>{t('Email updates to my verified account email','Taarifa kwenye email iliyothibitishwa ya akaunti yangu')}</label>}
 </>}</main>;
}
