export const POLICY_VERSION='2026-09-05-v2';
export const policies = {
 privacy: {en:'Privacy Policy',sw:'Sera ya Faragha', sections:[
 ['Data and purposes','Taarifa na matumizi','We use account name, verified sign-in identifiers and language to run your account; purchases, payment references and ledger records to deliver content and reconcile payments; and security events to prevent abuse. Public tipster names, biographies and published records are visible to visitors. Account contact details and payment data are private. Identity checks, when required, use restricted provider references rather than public document uploads.','Tunatumia jina, utambulisho wa kuingia uliothibitishwa na lugha kuendesha akaunti; manunuzi, kumbukumbu za malipo na leja kutoa maudhui na kuhakiki malipo; na matukio ya usalama kuzuia udanganyifu. Majina ya tipster, maelezo na rekodi zilizochapishwa ni za wazi. Mawasiliano na malipo ni binafsi. Ukaguzi wa utambulisho unapotakiwa hutumia kumbukumbu za mtoa huduma zenye ruhusa maalumu.'],
 ['Sharing and storage','Kushiriki na kuhifadhi','We use service providers to manage secure sign-in and store account data. Payment providers receive information necessary to process or verify purchases. Google or Apple receive sign-in requests only when you choose them. Staff access is limited by role; restricted reads and decisions are logged. Service locations and cross-border safeguards must be confirmed by the operator before launch. We do not sell personal data.','Tunatumia watoa huduma kusimamia kuingia kwa usalama na kuhifadhi taarifa za akaunti. Watoa huduma za malipo hupokea taarifa muhimu kwa malipo. Google au Apple hupokea ombi la kuingia ukizichagua. Ruhusa za wafanyakazi zinadhibitiwa na matendo nyeti yanarekodiwa. Mwendeshaji lazima athibitishe maeneo ya kuhifadhi na ulinzi wa uhamisho wa kimataifa kabla ya uzinduzi. Hatuuzi taarifa binafsi.'],
 ['Your choices and retention','Haki zako na uhifadhi','Use Account / Privacy to export account data, correct your details or request access, correction or deletion. Export is a convenient subset; request access for other records. Deletion requests are reviewed for legal holds, financial obligations and audit evidence. We remove unnecessary profile data while retaining justified financial, consent and immutable prediction records. Retention periods require documented operator approval; no statutory duration is asserted here. Requests can be escalated to the applicable data protection authority.','Tumia Akaunti / Faragha kupata nakala, kusahihisha au kuomba upatikanaji, marekebisho au ufutaji. Nakala ya moja kwa moja ni sehemu ya taarifa; omba upatikanaji kwa nyingine. Ufutaji hukaguliwa kwa wajibu wa kisheria, malipo na audit. Taarifa zisizohitajika huondolewa huku rekodi zinazohalalishwa zikihifadhiwa. Muda wa uhifadhi unahitaji uthibitisho wa mwendeshaji; hatudai muda maalumu wa sheria hapa. Malalamiko yanaweza kupelekwa kwa mamlaka ya ulinzi wa taarifa.']
 ]},
 terms:{en:'Terms of Use',sw:'Masharti ya Matumizi',sections:[
 ['The service','Huduma','Betslip Pro is an 18+ sports prediction and tipster marketplace. You buy access to Prediction or Betslip content. We do not accept betting stakes or pay betting winnings. Bookmaker names are reference labels, not partnerships. Odds and the TZS 1,000 reference payout are illustrations; actual bookmaker odds and returns may differ. No result or profit is guaranteed.','Betslip Pro ni soko la utabiri na tipsters kwa wenye miaka 18+. Unanunua maudhui ya Prediction au Betslip. Hatupokei dau wala kulipa ushindi wa betting. Majina ya bookmaker ni lebo, si ushirikiano. Odds na payout ya mfano ya TZS 1,000 ni makadirio; matokeo halisi yanaweza kutofautiana. Hakuna uhakika wa ushindi au faida.'],
 ['Accounts and purchases','Akaunti na manunuzi','Keep credentials secure and supply accurate information. Review price and content preview before payment. Paid selections are licensed for personal use, not redistribution. Access follows verified payment. Fraud, impersonation or abuse may lead to restriction with review through support. Statutory consumer rights are not excluded. Refund requests follow the Refund Policy and the in-app protection process.','Linda taarifa za kuingia na toa taarifa sahihi. Kagua bei na muhtasari kabla ya malipo. Maudhui ya kulipia ni kwa matumizi binafsi, si kusambaza. Access hutolewa baada ya malipo kuthibitishwa. Udanganyifu, kujifanya mtu mwingine au unyanyasaji vinaweza kusababisha vizuizi vinavyoweza kukaguliwa kupitia msaada. Haki za mlaji za kisheria haziondolewi. Refund hufuata sera na mchakato wa ulinzi kwenye app.'],
 ['Changes and disputes','Mabadiliko na migogoro','Material policy changes require acceptance of the current version before the next relevant transaction. Published prediction records remain immutable, including losses. Contact the operator through the account request workflow for account disputes and use Buyer Protection for purchase disputes. Applicable mandatory law prevails over these terms.','Mabadiliko muhimu ya sera yanahitaji kukubali toleo jipya kabla ya transaction inayohusika. Rekodi zilizochapishwa hazibadilishwi, hata zilizopoteza. Tumia maombi ya akaunti kwa migogoro ya akaunti na Ulinzi wa Mnunuzi kwa manunuzi. Sheria za lazima zina kipaumbele juu ya masharti haya.']
 ]},
 seller:{en:'Tipster / Seller Agreement',sw:'Mkataba wa Tipster / Muuzaji',sections:[
 ['Selling and earnings','Mauzo na mapato','Accept this agreement before submitting or selling. Tipster approval is separate from acceptance. The sale price is split 40% to the tipster and 60% to Betslip Pro; payment processing costs are recorded separately. Funds remain subject to payment verification, refunds, disputes and payout review. Tax rate, base and any platform-funded gross-up require confirmed tax configuration; no unverified withholding formula is promised.','Kubali mkataba kabla ya kuwasilisha au kuuza. Uidhinishaji wa tipster ni tofauti na acceptance. Bei hugawanywa 40% kwa tipster na 60% kwa Betslip Pro; gharama za processing huwekwa tofauti. Mapato hutegemea uthibitisho wa malipo, refund, migogoro na ukaguzi wa payout. Kiwango, msingi na gross-up ya kodi vinahitaji usanidi uliothibitishwa; hakuna formula isiyothibitishwa inayoahidiwa.'],
 ['Content and integrity','Maudhui na uadilifu','Submit original or properly licensed content before kickoff. You grant Betslip Pro permission to display and deliver it to buyers and preserve its performance record. Published verified slips cannot be edited or deleted. Uploaded Proof is user-supplied evidence and is not Verified. Never fabricate results, conceal losses, self-purchase, manipulate ratings or promise guaranteed winnings. Identity and payment checks may be required before payout. Restrictions and disputes are reviewed through support.','Wasilisha maudhui yako au yenye leseni kabla ya mechi. Unaruhusu Betslip Pro kuyaonyesha na kuwapa wanunuzi na kuhifadhi rekodi. Verified slips zilizochapishwa hazihaririwi wala kufutwa. Uploaded Proof ni ushahidi wa mtumiaji, si Verified. Usitengeneze matokeo bandia, kuficha hasara, kujinunulia, kubadili ratings kwa udanganyifu au kuahidi ushindi. Ukaguzi wa utambulisho na malipo unaweza kuhitajika kabla ya payout. Migogoro hukaguliwa kupitia msaada.']
 ]},
 refund:{en:'Refund & Cancellation Policy',sw:'Sera ya Refund na Kughairi',sections:[
 ['Request a review','Omba ukaguzi','Use Buyer Protection from your purchase for duplicate charges, unavailable or undelivered content, payment errors or misleading delivery. Include the purchase reference and facts; never send passwords or identity documents. Staff review payment and delivery evidence and record the decision. An approved refund is only marked refunded after a completed transfer reference is recorded.','Tumia Ulinzi wa Mnunuzi kwenye ununuzi kwa malipo mara mbili, maudhui yasiyofikika/yasiyotolewa, makosa ya malipo au utoaji unaopotosha. Weka reference na maelezo; usitume nenosiri au nyaraka za utambulisho. Wafanyakazi hukagua ushahidi na kurekodi uamuzi. Refund huwekwa imekamilika baada ya reference ya transfer iliyokamilika.'],
 ['Limits','Mipaka','A losing prediction or changed bookmaker odds alone does not establish failure to deliver purchased content. Requests to cancel already delivered digital content are reviewed under applicable consumer rights and the delivery circumstances. This policy does not waive mandatory remedies or promise a payment-provider processing time.','Utabiri uliopoteza au odds zilizobadilika pekee si kushindwa kutoa maudhui. Maombi ya kughairi maudhui yaliyotolewa hukaguliwa kwa haki za mlaji na mazingira ya utoaji. Sera haiondoi haki za lazima wala kuahidi muda wa processing wa mtoa malipo.']
 ]},
 responsible:{en:'Responsible Use / 18+',sw:'Matumizi ya Uwajibikaji / 18+',sections:[
 ['Keep control','Jidhibiti','Adults only. Predictions can be wrong and past performance does not guarantee future results. Never borrow money or chase losses. Set a spending limit and take breaks. If use causes distress, stop and seek support from someone you trust or a qualified support service. Request account restriction through Account / Privacy.','Watu wazima tu. Utabiri unaweza kukosea na historia si uhakika wa matokeo yajayo. Usikope wala kufukuzia hasara. Weka kikomo cha matumizi na pumzika. Ukipata msongo, acha na tafuta msaada kwa mtu unayemwamini au huduma inayofaa. Omba kuzuia akaunti kupitia Akaunti / Faragha.']
 ]},
 community:{en:'Community & Tipster Guidelines',sw:'Mwongozo wa Jamii na Tipsters',sections:[
 ['Fair participation','Ushiriki wa haki','No harassment, hate, impersonation, scams, illegal content, manipulated proof or guaranteed-win claims. Do not publish private account details, identity documents or others’ payment information. Label uploaded evidence honestly and respect content ownership. Report misconduct through Buyer Protection for purchases or an account request for privacy issues. Moderation may restrict access and preserve evidence for review.','Hakuna unyanyasaji, chuki, kujifanya mtu mwingine, utapeli, maudhui haramu, proof bandia au ahadi za ushindi wa lazima. Usichapishe taarifa binafsi, nyaraka za utambulisho au malipo ya wengine. Weka lebo sahihi kwa ushahidi na heshimu umiliki. Ripoti matatizo ya manunuzi kupitia Ulinzi wa Mnunuzi au maombi ya akaunti kwa faragha. Ukaguzi unaweza kuzuia access na kuhifadhi ushahidi.']
 ]},
 cookies:{en:'Cookie Policy',sw:'Sera ya Cookies',sections:[
 ['Essential storage only','Hifadhi muhimu tu','Essential sign-in cookies keep you signed in and protect the sign-in process. Local storage remembers your language preference. No optional analytics or advertising trackers are enabled by this release. Essential storage is necessary for requested account features. Clear it in your browser to remove local preferences; signing out clears the current session. Optional tracking must remain off until separately implemented with informed, revocable consent.','Cookies muhimu za kuingia zinakuhifadhi kwenye akaunti na kulinda mchakato wa kuingia. Local storage hukumbuka lugha. Toleo hili halina trackers za analytics au matangazo za hiari. Hifadhi muhimu inahitajika kwa akaunti. Futa kwenye browser kuondoa chaguo; kutoka huondoa session ya sasa. Tracking ya hiari lazima ibaki imezimwa mpaka iunganishwe na ridhaa inayoweza kuondolewa.']
 ]}
} as const;
